spring:
  application:
    name: exportify

  threads:
    virtual:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update


spotify-auth:
  redirect-uri: http://localhost:8080/authorize/callback
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  scopes:
    - app-remote-control
    - playlist-modify-private
    - playlist-modify-public
    - playlist-read-collaborative
    - playlist-read-private
    - streaming
    - ugc-image-upload
    - user-follow-modify
    - user-follow-read
    - user-library-modify
    - user-library-read
    - user-modify-playback-state
    - user-read-currently-playing
    - user-read-email
    - user-read-playback-position
    - user-read-playback-state
    - user-read-private
    - user-read-recently-played
    - user-top-read
