name: GraalVM Native Image builds
on:
  push:
    tags: ['**']
jobs:
  build:
    name: Exportify on ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build image
        run: ./gradlew clean

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: ./gradlew -Pversion==${GITHUB_REF##*/} bootBuildImage # --tags # --imageName==docker.io/library/${project.name}:${project.version}