name: GraalVM Native Image builds
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Exportify on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./mvnw

      - name: Build image
        run: ./mvnw clean install

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: ./mvnw clean package -DskipTests spring-boot:build-image -Drevision=${GITHUB_REF##*/} #-Dspring-boot.build-image.imageName=$IMAGE_REGISTRY:$IMAGE_TAG